'use strict';

/**
 * reengagement.js — (E7 / §E8) LLM re-engagement copy + programmatic reschedule-link
 * injection (WS-E-COPY).
 *
 * Produces the BODY of a re-engagement message for a volunteer whose appointment
 * didn't happen (missed-event escalation) or whose time fell through — a warm,
 * diplomatic nudge to pick a new time. The diplomatic prose is generated by a focused
 * Bedrock call; the reschedule link is injected PROGRAMMATICALLY so it is present in
 * EVERY output regardless of what the model returns (empty, garbage, adversarial, or a
 * failed/unwired Bedrock call).
 *
 *   generateReengagementCopy({ tenantId, booking, rescheduleUrl }, deps)
 *     → { subject, text_body, html_body }
 *
 * ── Ownership boundary (§E8, integrator-locked 2026-06-05) ──
 *   This module owns the BODY + the RESCHEDULE LINK only. It deliberately does NOT
 *   emit the STOP / unsubscribe footer — that footer is appended by notify.js's new
 *   `reengagement` kind (integrator glue), the single place STOP/unsubscribe lives, so
 *   the compliance footer is never double-injected or divergent. The integrator glue
 *   takes { subject, text_body, html_body } from here, appends STOP/unsubscribe, sets
 *   the recipient, and dispatches via the send_email Lambda (mirrors notify.js).
 *
 * ── The compliance invariant this module guarantees (audit target) ──
 *   The reschedule link appears in BOTH text_body and html_body of EVERY successful
 *   return. It is injected AFTER the model step from the caller-supplied (https-only,
 *   validated) URL — never sourced from model output — so a model that returns nothing,
 *   garbage, a prompt-injection payload, or a hostile URL cannot remove or replace it.
 *   A MISSING/INVALID reschedule URL is a caller contract error → THROW (re-engagement
 *   copy with no reschedule path would itself violate the invariant), mirroring
 *   notify.js buildEmailPayload's throw-on-missing-required-link (§B8).
 *
 * ── "Never 'no availability'" ──
 *   Enforced by (a) the system prompt forbidding any unavailability framing, and
 *   (b) a deterministic fallback body that is itself diplomatic and never says it.
 *   It is NOT enforced by post-hoc string-scrubbing of model output — that would be
 *   brittle; the prompt + safe fallback are the controls. (Stated for the audit.)
 *
 * ── Bedrock dependency (FLAGGED for integrator) ──
 *   `@aws-sdk/client-bedrock-runtime` is NOT in this library's package.json (deps are
 *   integrator-owned; workstreams never edit package.json — README rule). So the model
 *   call is a DI seam: `deps.invokeModel` is injected in tests; the default impl
 *   lazy-requires the SDK only when actually called. Integrator wiring owed:
 *     1. add `@aws-sdk/client-bedrock-runtime` to shared/scheduling/package.json,
 *     2. grant `bedrock:InvokeModel` on the host Lambda role,
 *     3. set REENGAGEMENT_MODEL_ID (or BEDROCK_MODEL_ID) on that Lambda.
 *   Until wired, the model call throws → caught → deterministic fallback copy (still
 *   carries the reschedule link), so the module is safe to ship ahead of the wiring.
 *
 * ── DI seam ──
 *   deps = { invokeModel, log }. Fully unit-testable without AWS — the default
 *   invokeModel is the only AWS-touching code and is never loaded in tests.
 */

// Model id is env-driven (repo convention — see reference_bsh_requires_bedrock_model_id_env);
// no hardcoded default, so a misconfigured deploy fails the model call (→ fallback) rather
// than silently calling an unintended model.
const MODEL_ID = process.env.REENGAGEMENT_MODEL_ID || process.env.BEDROCK_MODEL_ID || '';
const MAX_MODEL_TOKENS = 256;
// Bound the prose we accept back from the model (defense + email-size sanity).
const MAX_BODY_CHARS = 1500;

// ─── small helpers ───────────────────────────────────────────────────────────────────

function escapeHtml(s) {
  return String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[c]));
}

// Forward-compatible read: accept the in-memory camelCase booking OR a DDB snake_case
// row (schema discipline — tolerate either; missing → undefined).
function pick(booking, camel, snake) {
  if (!booking) return undefined;
  return booking[camel] != null ? booking[camel] : booking[snake];
}

function firstNameOf(fullName) {
  if (typeof fullName !== 'string') return '';
  return fullName.trim().split(/\s+/)[0] || '';
}

// https-only gate (mirrors notify.js safeUrl): a non-https scheme (javascript:/data:/
// mailto:/…) is dropped to '' so a malformed or hostile link can never become an href.
function safeUrl(url) {
  if (typeof url !== 'string') return '';
  const t = url.trim();
  // Reject ANY embedded whitespace: a value like 'https://real\nhttps://evil' would
  // otherwise pass the prefix test and put a second clickable URL in the body.
  if (/\s/.test(t)) return '';
  return /^https:\/\//i.test(t) ? t : '';
}

// Strip control chars (keep \n,\t) + zero-width unicode. Shared by prompt-input and
// model-output sanitization (defense-in-depth, mirrors §B5 sub-steps b).
function stripUnsafeChars(s) {
  return String(s == null ? '' : s)
    .replace(/[\u0000-\u0008\u000B-\u001F\u007F]/g, '') // incl. \r (\u000D); keeps \t,\n
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    // Bidi control/override/isolate chars (visual spoofing in subject + body).
    .replace(/[\u200E\u200F\u202A-\u202E\u2066-\u2069]/g, '')
    // Unicode line/paragraph separators (inconsistent SMTP/MIME handling).
    .replace(/[\u2028\u2029]/g, '');
}

// Sanitize a booking value before interpolating it into the model prompt. Booking
// fields (name/org) can originate from attacker-controlled form data (§B5), so neutralize
// structural-injection markers + cap length before they reach the prompt.
function sanitizeForPrompt(value, maxLen) {
  let s = stripUnsafeChars(value);
  s = s.replace(/<\/?(?:system|context|user_application_context)>/gi, '');
  s = s.replace(/\[\/?INST\]/gi, '');
  // Llama-family system markers (defense-in-depth if the model is ever swapped).
  s = s.replace(/<<\/?\s*SYS\s*>>/gi, '');
  // Strip any remaining HTML tags so attacker markup never reaches the prompt (and
  // can't be echoed raw into the text/plain body). Defense-in-depth atop the API's
  // structural system/user-turn isolation.
  s = s.replace(/<[^>]*>/g, '');
  s = s.replace(/\s+/g, ' ').trim();
  if (s.length > maxLen) s = s.slice(0, maxLen).trim();
  return s;
}

// Sanitize prose returned by the model before it lands in an email body. Returns '' for
// empty/whitespace-only (→ caller substitutes the deterministic fallback).
function sanitizeModelText(text) {
  // Non-string returns (number/object/etc. from an injected invokeModel) become empty
  // -> the deterministic fallback fires (parity with defaultInvokeModel's typeof guard).
  if (typeof text !== 'string') return '';
  let s = stripUnsafeChars(text);
  // Strip HTML tags from model output so raw markup (e.g. <script>...) never reaches
  // the text/plain body (html_body is escaped separately). Mirrors sanitizeForPrompt.
  s = s.replace(/<[^>]*>/g, '');
  // Strip any bare URL the model emitted despite the prompt's "no URLs" rule. The
  // authoritative reschedule link is injected programmatically AFTER this step; a URL
  // left in prose is model non-compliance or a prompt-injection artifact, and email
  // clients auto-linkify bare URLs in a text/plain body -> a competing clickable link.
  s = s.replace(/\bhttps?:\/\/\S+/gi, '[link removed]');
  s = s.replace(/\n{3,}/g, '\n\n').trim();
  if (s.length > MAX_BODY_CHARS) s = s.slice(0, MAX_BODY_CHARS).trim();
  return s;
}

// ─── prompt + fallback ────────────────────────────────────────────────────────────────

const SYSTEM_PROMPT =
  'You write a brief, warm re-engagement message body for a nonprofit volunteer ' +
  'scheduling assistant. Tone: diplomatic, appreciative, encouraging. Rules: ' +
  'write 2-3 short sentences; address the volunteer by first name if one is given; ' +
  'invite them to pick a new time for their appointment. NEVER state or imply that ' +
  'there is no availability or that no times are open — always frame finding a new ' +
  'time as easy and welcome. Do NOT include any URL, link, button, signature, or any ' +
  '"reply STOP"/unsubscribe text — those are added separately. Output ONLY the message ' +
  'body as plain text.';

function buildUserPrompt({ firstName, org, apptType }) {
  return (
    `Volunteer first name: ${firstName || '(none given)'}\n` +
    `Organization: ${org}\n` +
    `Appointment type: ${apptType}\n\n` +
    'Write the re-engagement message body.'
  );
}

// Deterministic, diplomatic fallback — used when the model returns nothing usable or
// the model call fails. Never references unavailability.
function fallbackBody({ firstName, apptType }) {
  const greeting = firstName ? `Hi ${firstName},` : 'Hi there,';
  return (
    `${greeting} we'd still love to connect with you about your ${apptType}. ` +
    "Whenever you're ready, it's easy to pick a time that works better for you."
  );
}

// ─── default DI implementation (the only AWS-touching code; lazy-required) ─────────────

/**
 * Default Bedrock invocation — Anthropic Messages API via InvokeModel. Lazy-requires the
 * SDK so the module loads (and tests run) without `@aws-sdk/client-bedrock-runtime`
 * installed. Returns the model's text. Throws on any failure (no model id, missing dep,
 * IAM denial, unparseable response) — the caller catches and falls back.
 */
async function defaultInvokeModel({ system, prompt, maxTokens }) {
  if (!MODEL_ID) {
    throw new Error('no model id configured (set REENGAGEMENT_MODEL_ID or BEDROCK_MODEL_ID)');
  }
  // eslint-disable-next-line global-require -- lazy: dep not in package.json (integrator-owned)
  const { BedrockRuntimeClient, InvokeModelCommand } = require('@aws-sdk/client-bedrock-runtime');
  const client = new BedrockRuntimeClient({});
  const res = await client.send(
    new InvokeModelCommand({
      modelId: MODEL_ID,
      contentType: 'application/json',
      accept: 'application/json',
      body: JSON.stringify({
        anthropic_version: 'bedrock-2023-05-31',
        max_tokens: maxTokens ?? MAX_MODEL_TOKENS,
        system,
        messages: [{ role: 'user', content: prompt }],
      }),
    })
  );
  if (!res || res.body == null) {
    throw new Error('empty Bedrock response');
  }
  const parsed = JSON.parse(Buffer.from(res.body).toString('utf8'));
  const text = parsed && Array.isArray(parsed.content) && parsed.content[0]
    ? parsed.content[0].text
    : '';
  return typeof text === 'string' ? text : '';
}

// ─── generateReengagementCopy ───────────────────────────────────────────────────────────

/**
 * @param {{ tenantId: string, booking: object, rescheduleUrl?: string }} args
 *   rescheduleUrl: explicit https URL; falls back to booking.rescheduleUrl /
 *   booking.reschedule_url. REQUIRED (throws if missing/non-https).
 * @param {object} [deps] - { invokeModel, log }
 * @returns {Promise<{ subject: string, text_body: string, html_body: string }>}
 *   text_body/html_body always contain the reschedule link; NO STOP/unsubscribe footer
 *   (notify.js appends it).
 */
async function generateReengagementCopy({ tenantId, booking, rescheduleUrl } = {}, deps = {}) {
  const { invokeModel = defaultInvokeModel, log = console } = deps;

  if (!tenantId) {
    throw new Error('tenantId is required');
  }

  // Compliance invariant: a re-engagement message MUST carry a reschedule path. A
  // missing/invalid (non-https) URL is a caller contract error, not a degrade case.
  const url = safeUrl(rescheduleUrl) || safeUrl(pick(booking, 'rescheduleUrl', 'reschedule_url'));
  if (!url) {
    throw new Error('generateReengagementCopy requires an https rescheduleUrl');
  }

  const firstName = sanitizeForPrompt(
    pick(booking, 'attendeeFirstName', 'attendee_first_name') ||
      firstNameOf(pick(booking, 'attendeeName', 'attendee_name')),
    50
  );
  const orgKnown = sanitizeForPrompt(
    pick(booking, 'organizationName', 'organization_name') ||
      pick(booking, 'orgName', 'org_name') ||
      '',
    50
  );
  const org = orgKnown || 'your organization';
  const apptType = sanitizeForPrompt(
    pick(booking, 'appointmentTypeName', 'appointment_type_name') || 'appointment',
    60
  );

  // Generate the diplomatic prose; ANY failure degrades to the deterministic fallback.
  // The reschedule link is injected afterward regardless, so the invariant holds.
  let prose = '';
  try {
    const raw = await invokeModel({
      system: SYSTEM_PROMPT,
      prompt: buildUserPrompt({ firstName, org, apptType }),
      maxTokens: MAX_MODEL_TOKENS,
      tenantId,
    });
    prose = sanitizeModelText(raw);
  } catch (err) {
    log.warn(
      `[reengagement] model call failed for tenant=${tenantId} — using fallback copy: ${err.message}`
    );
  }
  if (!prose) {
    prose = fallbackBody({ firstName, apptType });
  }

  // Programmatic reschedule-link injection — authoritative, never from model output.
  const text_body = `${prose}\n\nPick a new time here: ${url}`;
  const html_body =
    `<p>${escapeHtml(prose).replace(/\n+/g, '</p><p>')}</p>` +
    `<p>Pick a new time here: <a href="${escapeHtml(url)}">Choose a new time</a></p>`;

  // Omit the org suffix when the booking has no real org name (avoids a broken
  // "works — your organization" default subject).
  const subject = orgKnown
    ? `Let's find a time that works — ${orgKnown}`
    : "Let's find a time that works";

  return { subject, text_body, html_body };
}

module.exports = {
  generateReengagementCopy,
  // exported for unit coverage + reuse:
  defaultInvokeModel,
  sanitizeForPrompt,
  sanitizeModelText,
  fallbackBody,
  safeUrl,
  escapeHtml,
  SYSTEM_PROMPT,
  _MODEL_ID: MODEL_ID,
};
